const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

const generateStudentReport = async (student, data, filePath) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const stream = fs.createWriteStream(filePath);

    doc.pipe(stream);

    // Header
    doc
      .fillColor('#2c3e50')
      .fontSize(20)
      .text('STUDENT PERFORMANCE REPORT', { align: 'center' })
      .moveDown();

    doc
      .strokeColor('#27ae60')
      .lineWidth(2)
      .moveTo(50, 80)
      .lineTo(550, 80)
      .stroke();

    doc.moveDown(2);

    // Student Info
    doc.fillColor('#000').fontSize(12);
    doc.text(`Name: ${student.name}`, { bold: true });
    doc.text(`Student ID: ${student.studentId}`);
    doc.text(`Department: ${student.dept}`);
    doc.text(`Section: ${student.sec}`);
    doc.text(`Risk Level: ${student.academicRisk || 'Green'}`, {
      color: student.academicRisk === 'Red' ? '#e74c3c' : student.academicRisk === 'Yellow' ? '#f1c40f' : '#27ae60'
    });
    
    doc.moveDown();

    // Attendance Summary
    doc.fontSize(14).text('Attendance Summary', { underline: true }).moveDown(0.5);
    doc.fontSize(12).text(`Total Attendance Rate: ${(data.attendanceRate * 100).toFixed(2)}%`);
    doc.moveDown();

    // Marks Summary
    doc.fontSize(14).text('Academic Performance', { underline: true }).moveDown(0.5);
    doc.fontSize(12).text(`Midterm Performance: ${(data.midtermScore * 100).toFixed(2)}%`);
    doc.fontSize(12).text(`Quiz Completion: ${(data.quizRate * 100).toFixed(2)}%`);
    doc.moveDown();

    // AI Prediction
    doc.fontSize(14).text('AI Academic Prediction', { underline: true }).moveDown(0.5);
    doc.fontSize(12).text(`Prediction Probability: ${(data.predictionGrade * 100).toFixed(2)}%`);
    doc.fontSize(12).text(`Suggested Action: ${data.suggestion || 'Continue regular study'}`);

    // Footer
    const bottom = doc.page.height - 100;
    doc
      .fontSize(10)
      .fillColor('#7f8c8d')
      .text('This is an automated report generated by the AI Student Management System.', 50, bottom, { align: 'center', width: 500 });

    doc.end();

    stream.on('finish', () => resolve(filePath));
    stream.on('error', reject);
  });
};

module.exports = { generateStudentReport };
