services:
  - type: web
    name: student-management-system
    env: node
    region: oregon
    branch: main
    buildCommand: npm run install-all && npm run build
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        value: "mongodb+srv://prasanthsaiponna_db_user:prasanth2006@cluster0.pk8beau.mongodb.net/student-management?retryWrites=true&w=majority"
      - key: PORT
        value: "5000"
      - key: JWT_SECRET
        value: "supersecretvalue"
      - key: NODE_ENV
        value: "production"